### ISSUE TITLE
[BUG] Light API not working on paper 1.18.2

### ISSUE THREAD

**Issue by fnrcum** [BeYkeRYkt/LightAPI#29]
Like in the title, the LightAPI currently does not work on paper 1.18.2
```ps1
[13:43:19] [Server thread/INFO]: [LightAPI] Enabling LightAPI vbukkit-5.1.0 (build SNAPSHOT)
[13:43:19] [Server thread/INFO]: <LightAPI>: [INFO] Initializing LightAPI...
[13:43:19] [Server thread/WARN]: java.lang.ClassNotFoundException: ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.nms.v1_18_R2.StarlightNMSHandler
[13:43:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[13:43:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[13:43:19] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[13:43:19] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[13:43:19] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[13:43:19] [Server thread/WARN]: 	at LightAPI-Bukkit-5.1.0.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.HandlerFactory.createHandler(HandlerFactory.java:71)
[13:43:19] [Server thread/WARN]: 	at LightAPI-Bukkit-5.1.0.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.BukkitPlatformImpl.initHandler(BukkitPlatformImpl.java:196)
[13:43:19] [Server thread/WARN]: 	at LightAPI-Bukkit-5.1.0.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.BukkitPlatformImpl.initialization(BukkitPlatformImpl.java:228)
[13:43:19] [Server thread/WARN]: 	at LightAPI-Bukkit-5.1.0.jar//ru.beykerykt.minecraft.lightapi.common.LightAPI.initialization(LightAPI.java:88)
[13:43:19] [Server thread/WARN]: 	at LightAPI-Bukkit-5.1.0.jar//ru.beykerykt.minecraft.lightapi.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:70)
[13:43:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:43:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[13:43:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[13:43:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[13:43:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[13:43:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666)
[13:43:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433)
[13:43:19] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[13:43:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)
[13:43:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[13:43:19] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[13:43:19] [Server thread/WARN]: java.lang.IllegalStateException: Initialization failed! Code: -1
[13:43:19] [Server thread/WARN]: 	at LightAPI-Bukkit-5.1.0.jar//ru.beykerykt.minecraft.lightapi.common.LightAPI.initialization(LightAPI.java:96)
[13:43:19] [Server thread/WARN]: 	at LightAPI-Bukkit-5.1.0.jar//ru.beykerykt.minecraft.lightapi.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:70)
[13:43:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:43:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[13:43:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[13:43:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[13:43:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[13:43:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666)
[13:43:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433)
[13:43:19] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[13:43:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)
[13:43:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[13:43:19] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[13:43:19] [Server thread/INFO]: [LightAPI] Disabling LightAPI vbukkit-5.1.0 (build SNAPSHOT)
```

**Comment by jonaas13** [comment]
@BeYkeRYkt Any eta to when this will be fixed?

**Comment by PaladinFallen** [comment]
Getting the same warnings as well..

**Comment by BeYkeRYkt** [comment]
Update coming soon

**Comment by ErythroCraft** [comment]
Light API not working on spigot 1.18.2

[18:20:27] [Server thread/INFO]: [LightAPI] Enabling LightAPI vbukkit-5.1.0 (build SNAPSHOT)
[18:20:27] [Server thread/INFO]: <LightAPI>: [INFO] Initializing LightAPI...

- [ ] [18:20:27] [Server thread/WARN]: java.lang.ClassNotFoundException: ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.nms.v1_18_R2.VanillaNMSHandler

[18:20:27] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[18:20:27] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[18:20:27] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[18:20:27] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[18:20:27] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[18:20:27] [Server thread/WARN]:        at ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.HandlerFactory.createHandler(HandlerFactory.java:71)
[18:20:27] [Server thread/WARN]:        at ru.beykerykt.minecraft.lightapi.bukkit.internal.BukkitPlatformImpl.initHandler(BukkitPlatformImpl.java:196)
[18:20:27] [Server thread/WARN]:        at ru.beykerykt.minecraft.lightapi.bukkit.internal.BukkitPlatformImpl.initialization(BukkitPlatformImpl.java:228)
[18:20:27] [Server thread/WARN]:        at ru.beykerykt.minecraft.lightapi.common.LightAPI.initialization(LightAPI.java:88)
[18:20:27] [Server thread/WARN]:        at ru.beykerykt.minecraft.lightapi.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:70)
[18:20:27] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:20:27] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[18:20:27] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[18:20:27] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:517)
[18:20:27] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:431)
[18:20:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612)
[18:20:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[18:20:27] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263)
[18:20:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007)
[18:20:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[18:20:27] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

- [ ] **[18:20:27] [Server thread/WARN]: java.lang.IllegalStateException: Initialization failed! Code: -1**

[18:20:27] [Server thread/WARN]:        at ru.beykerykt.minecraft.lightapi.common.LightAPI.initialization(LightAPI.java:96)
[18:20:27] [Server thread/WARN]:        at ru.beykerykt.minecraft.lightapi.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:70)
[18:20:27] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:20:27] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[18:20:27] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[18:20:27] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:517)
[18:20:27] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:431)
[18:20:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612)
[18:20:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[18:20:27] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263)
[18:20:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007)
[18:20:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[18:20:27] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:20:27] [Server thread/INFO]: [LightAPI] Disabling LightAPI vbukkit-5.1.0 (build SNAPSHOT)

- [ ] **[18:20:27] [Server thread/INFO]: <LightAPI>: [INFO] Disabling the plugin is allowed only to the implementation class**

**Comment by ErythroCraft** [comment]
https://www.geeksforgeeks.org/how-to-solve-java-lang-illegalstateexception-in-java-main-thread/

**Comment by Iuriiiii** [comment]
I tried to import the LightAPI project on Eclipse and IntelliJ exhaustively to fix it, but it was impossible. I will stay waiting for the last update.

**Comment by saucesteals** [comment]
@Iuriiiii I saw a bunch of commits from January and a couple from the day that @BeYkeRYkt said there would be an update soon so I assumed they had fixed the problem and attempted to compile + package myself but it truly was impossible

**Comment by nhanledev** [comment]
I hope this can be fixed soon

**Comment by myavuzokumus** [comment]
Any ETA?

**Comment by joaoespanhol** [comment]
update github, is no same update spigot, why?

@BeYkeRYkt

**Comment by Chris6ix** [comment]
Any updates on this?
LightAPI is the only thing keeping my Server from updating to 1.18.2...

**Comment by D-Volk** [comment]
Waiting update...

**Comment by Iuriiiii** [comment]
Can anyone export the project from IntelliJ to Eclipse? I will try to update it by myself

**Comment by purejosh** [comment]
Heh, I was going to open a ticket, or bump an open one about 1.18.2, but it appears that many others have done so. 

I hope the update goes smoothly. Thanks, devs.

**Comment by notbike** [comment]
same problem here

**Comment by Dymeth** [comment]
Updated, see https://github.com/BeYkeRYkt/LightAPI/releases
Thank you, [BeYkeRYkt](https://github.com/BeYkeRYkt) <3

**Comment by Chris6ix** [comment]
Thanks @BeYkeRYkt for updating :)
