### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by Dymeth** [BeYkeRYkt/LightAPI#31]
```[LightAPI] Enabling LightAPI vbukkit-5.2.0 (build SNAPSHOT)
<LightAPI>: [INFO] Initializing LightAPI...
java.lang.ClassNotFoundException: ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.nms.v1_19_R1.StarlightNMSHandler
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at LightAPI-Bukkit-5.2.0.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.HandlerFactory.createHandler(HandlerFactory.java:71)
	at LightAPI-Bukkit-5.2.0.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.BukkitPlatformImpl.initHandler(BukkitPlatformImpl.java:196)
	at LightAPI-Bukkit-5.2.0.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.BukkitPlatformImpl.initialization(BukkitPlatformImpl.java:228)
	at LightAPI-Bukkit-5.2.0.jar//ru.beykerykt.minecraft.lightapi.common.LightAPI.initialization(LightAPI.java:88)
	at LightAPI-Bukkit-5.2.0.jar//ru.beykerykt.minecraft.lightapi.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:70)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554)
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1121)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.IllegalStateException: Initialization failed! Code: -1
	at LightAPI-Bukkit-5.2.0.jar//ru.beykerykt.minecraft.lightapi.common.LightAPI.initialization(LightAPI.java:96)
	at LightAPI-Bukkit-5.2.0.jar//ru.beykerykt.minecraft.lightapi.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:70)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554)
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1121)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
	at java.base/java.lang.Thread.run(Thread.java:833)
[LightAPI] Disabling LightAPI vbukkit-5.2.0 (build SNAPSHOT)
<LightAPI>: [INFO] Shutdown LightAPI...
```

**Comment by VergilPrime** [comment]
Yes please!

**Comment by BeYkeRYkt** [comment]
Soon

**Comment by Dymeth** [comment]
https://www.spigotmc.org/resources/lightapi.4510/update?update=465301
