### ISSUE TITLE
Getting "java.lang.IllegalStateException: Singleton not yet initialized! Use prepare()" when launching server

### ISSUE THREAD

**Issue by DropOfAWater** [BeYkeRYkt/LightAPI#34]
When launching server I am getting this error:
```
java.lang.IllegalStateException: Singleton not yet initialized! Use prepare() !
        at ru.beykerykt.minecraft.lightapi.common.LightAPI.get(LightAPI.java:122) ~[?:?]
        at me.a_drop_of_water.Main.onEnable(Main.java:20) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:507) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3443-Bukkit-2c1e499]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:433) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3443-Bukkit-2c1e499]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:602) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3443-Bukkit-2c1e499]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:404) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3443-Bukkit-2c1e499]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:249) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3443-Bukkit-2c1e499]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:971) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3443-Bukkit-2c1e499]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:294) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3443-Bukkit-2c1e499]
```
How can I solve this issue?

**Comment by chrisgdt** [comment]
Use 1.18.2 on your server, 1.18.1 is a dead version.

**Comment by Lycheeeees** [comment]
This is also an issue in 1.16.5

**Comment by BeYkeRYkt** [comment]
Issue closed: LightAPI is no longer being maintained. Use LightBlock instead
