### ISSUE TITLE
error  Initializing LightAPI...

### ISSUE THREAD

**Issue by PouleyXYZ** [BeYkeRYkt/LightAPI#42]
```
[13:29:03 INFO]: <LightAPI>: [INFO] Initializing LightAPI...
[13:29:03 WARN]: java.lang.ClassNotFoundException: ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.nms.v1_19_R2.StarlightNMSHandler
[13:29:03 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:177)
[13:29:03 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124)
[13:29:03 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[13:29:03 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[13:29:03 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[13:29:03 WARN]:        at LightAPI-Bukkit-5.3.0.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.HandlerFactory.createHandler(HandlerFactory.java:71)
[13:29:03 WARN]:        at LightAPI-Bukkit-5.3.0.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.BukkitPlatformImpl.initHandler(BukkitPlatformImpl.java:196)
[13:29:03 WARN]:        at LightAPI-Bukkit-5.3.0.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.BukkitPlatformImpl.initialization(BukkitPlatformImpl.java:228)
[13:29:03 WARN]:        at LightAPI-Bukkit-5.3.0.jar//ru.beykerykt.minecraft.lightapi.common.LightAPI.initialization(LightAPI.java:88)
[13:29:03 WARN]:        at LightAPI-Bukkit-5.3.0.jar//ru.beykerykt.minecraft.lightapi.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:70)
[13:29:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:29:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
[13:29:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544)
[13:29:03 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578)
[13:29:03 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492)
[13:29:03 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[13:29:03 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[13:29:03 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:301)
[13:29:03 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[13:29:03 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:29:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:29:03 WARN]: java.lang.IllegalStateException: Initialization failed! Code: -1
[13:29:03 WARN]:        at LightAPI-Bukkit-5.3.0.jar//ru.beykerykt.minecraft.lightapi.common.LightAPI.initialization(LightAPI.java:96)
[13:29:03 WARN]:        at LightAPI-Bukkit-5.3.0.jar//ru.beykerykt.minecraft.lightapi.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:70)
[13:29:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:29:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
[13:29:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544)
[13:29:03 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578)
[13:29:03 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492)
[13:29:03 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[13:29:03 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[13:29:03 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:301)
[13:29:03 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[13:29:03 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:29:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:29:03 INFO]: [LightAPI] Disabling LightAPI vbukkit-5.3.0 (build SNAPSHOT)
```

**Comment by TheFaik** [comment]
+

**Comment by MegDuck** [comment]
same

**Comment by Sebo-sudo** [comment]
This is happening to me too!

**Comment by zikehalil3535** [comment]
Same

**Comment by vpttyn** [comment]
samee

**Comment by C1pher0** [comment]
You guys are not using a supported version it seems.

**Comment by BeYkeRYkt** [comment]
Issue closed: LightAPI is no longer being maintained.
