### ISSUE TITLE
NPEs with Spigot 1.12

### ISSUE THREAD

**Issue by SlimeDog** [BeYkeRYkt/LightAPI#7]
Spigot 1.12-pre2
LightAPI 3.2.4
ShinyItems 1.6.1

NPE using ShinyItems torch
> [08:13:02] [Server thread/WARN]: [ShinyItems] Task #28 for ShinyItems v1.6.1 generated an exception
java.lang.NullPointerException: null
        at ru.beykerykt.lightapi.LightAPI.collectChunks(LightAPI.java:248) ~[?:?]
        at io.github.sipsi133.ShinyItems.update(ShinyItems.java:664) ~[?:?]
        at io.github.sipsi133.ShinyItems.handleRemove(ShinyItems.java:195) ~[?:?]
        at io.github.sipsi133.ShinyItems$1.run(ShinyItems.java:167) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

NPE on disable/shutdown
> [08:13:05] [Server thread/INFO]: [ShinyItems] Disabling ShinyItems v1.6.1
[08:13:05] [Server thread/ERROR]: Error occurred while disabling ShinyItems v1.6.1 (Is it up to date?)
java.lang.NullPointerException: null
        at ru.beykerykt.lightapi.LightAPI.deleteLight(LightAPI.java:235) ~[?:?]
        at ru.beykerykt.lightapi.LightAPI.deleteLight(LightAPI.java:217) ~[?:?]
        at io.github.sipsi133.ShinyItems.onDisable(ShinyItems.java:260) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:414) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:345) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
        at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:464) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by SlimeDog** [comment]
Same issue with Spigot 1.12 production release.

**Comment by egg82** [comment]
Adding to this since this same error seems to have changed slightly.

Edit: Hastebin available [here](https://hastebin.com/etuzoyupix.vbs) because formatting.

`org.bukkit.command.CommandException: Unhandled exception executing command 'hat' in plugin HatMeEnhanced v3.1.16
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.jar:git-Spigot-99c2a37-f078eed]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:435) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:424) [EssentialsX-2.0.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.12.jar:git-Spigot-99c2a37-f078eed]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.12.jar:git-Spigot-99c2a37-f078eed]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.12.jar:git-Spigot-99c2a37-f078eed]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot-1.12.jar:git-Spigot-99c2a37-f078eed]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot-1.12.jar:git-Spigot-99c2a37-f078eed]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.jar:git-Spigot-99c2a37-f078eed]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.jar:git-Spigot-99c2a37-f078eed]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-99c2a37-f078eed]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-99c2a37-f078eed]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-99c2a37-f078eed]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-99c2a37-f078eed]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-99c2a37-f078eed]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-99c2a37-f078eed]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at ru.beykerykt.lightapi.LightAPI.createLight(LightAPI.java:208) ~[?:?]
        at ru.beykerykt.lightapi.LightAPI.createLight(LightAPI.java:184) ~[?:?]
        at me.egg82.hme.reflection.light.LightAPIHelper.addLight(LightAPIHelper.java:26) ~[?:?]
        at me.egg82.hme.commands.HatCommand.hat(HatCommand.java:316) ~[?:?]
        at me.egg82.hme.commands.HatCommand.onExecute(HatCommand.java:188) ~[?:?]
        at me.egg82.hme.lib.ninja.egg82.patterns.SynchronousCommand.start(SynchronousCommand.java:40) ~[?:?]
        at me.egg82.hme.lib.ninja.egg82.plugin.handlers.CommandHandler.runCommand(CommandHandler.java:82) ~[?:?]
        at me.egg82.hme.lib.ninja.egg82.plugin.BasePlugin.onCommand(BasePlugin.java:114) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.jar:git-Spigot-99c2a37-f078eed]
        ... 18 more`
